### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Yuma6128** [Yuma6128/furima-36167#20]
# URL
https://furima-36167.herokuapp.com/

# Basic認証
ID : admin
PASS : 2222

# 出品者
mail : test@email.com
pass : test1234

# 購入者
mail : test1@email
pass : test1234

**Comment by mo1015** [comment]
ご提出ありがとうございます！ お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **商品が出品されていない状態では、ダミーの商品情報が表示されるようにしましょう**

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Yuma6128** [comment]
> ご提出ありがとうございます！ お待たせいたしました。 動作の確認をしたところ、修正していただきたい箇所がございました。 以下のご確認をお願いします！
> 
> [修正依頼箇所]
> 
> * [ ]  **商品が出品されていない状態では、ダミーの商品情報が表示されるようにしましょう**
> 
> 修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！ ※新しいissueを作っていただく必要はございません。 https://forms.gle/dYuR1wjeHepbEhU7A

こちら修正いたしました。
データが入っているようでしたが、一度リセット必要でしょうか？

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。

> データが入っているようでしたが、一度リセット必要でしょうか？

修正ありがとうございます🎉データベースをリセットしてからの確認となりますので、
動作確認で使用させていただいたデータはリセットしてから再提出をお願いします！
お手数おかけしますがよろしくお願いいたします。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Yuma6128** [comment]
データリセットして、再度申請いたしました。
# URL
https://furima-36167.herokuapp.com/

# Basic認証
ID : admin
PASS : 2222

# 出品者
mail : test@email.com
pass : test1234

# 購入者
mail : test1@email
pass : test1234

**Comment by mo1015** [comment]
データベースのリセットと再提出ありがとうございます！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/136314176-5febad53-437d-47f5-967b-add36f293f94.png)
